### ISSUE TITLE
AUROC hangs in main_linear.py with finetune=True

### ISSUE THREAD

**Issue by kivanctezoren** [KarahanS/Self-Supervised-Learning-for-Medical-Image-Analysis#38]
Possibly due to the altered dataloaders, on organXmnist, tissuemnist and pathmnist, execution hangs on AUROC calculation after training and testing is done in [main_linear.py](https://github.com/KarahanS/Self-Supervised-Learning-for-Medical-Image-Analysis/blob/main/main_linear.py) when `finetune` is `True`, and the process is eventually killed.

Temporary Workaround: Use [main_linear_evaluate.py](https://github.com/KarahanS/Self-Supervised-Learning-for-Medical-Image-Analysis/blob/main_linear_evaluate/main_linear_evaluate.py), a modified `main_linear.py` that loads the trained LinearModel, skips training, evaluates test accuracies and AUROC, and logs to wandb. **Set with `finetune=False`.**

**Comment by KarahanS** [comment]
When you sort the datasets according to the test set sizes, organXmnist, tissuemnist and pathmnist are the first 4 ones. So probably, the process was killed by kernel due to out of memory. While calculating the AUROC, storing tensors into a list caused us to store the entire computation graph as well, which consumes significant memory. Solved the issue by `detach`ing the tensors from the GPU.

Branch: https://github.com/KarahanS/Self-Supervised-Learning-for-Medical-Image-Analysis/tree/supervised
